// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package container

import (
	"gorm.io/gorm"
	"sc-backend_task.com/task_1/internal/adapter/db/repository"
	"sc-backend_task.com/task_1/internal/interface/api"
	"sc-backend_task.com/task_1/internal/usecase"
)

// Injectors from wire.go:

func WireStudentApi(db *gorm.DB) api.StudentController {
	studentRepository := repository.ProvideStudentRepository(db)
	findAllStudent := usecase.ProvideFindAllStudent(studentRepository)
	findStudentById := usecase.ProvideFindStudentById(studentRepository)
	createStudent := usecase.ProvideCreateStudent(studentRepository)
	deleteStudent := usecase.ProvideDeleteStudent(studentRepository)
	putStudent := usecase.ProvidePutStudent(studentRepository)
	patchStudent := usecase.ProvidePatchStudent(studentRepository)
	studentController := api.ProvideStudentController(findAllStudent, findStudentById, createStudent, deleteStudent, putStudent, patchStudent)
	return studentController
}
